#let journal-abbrev-map = (
  "Annual Review of Fluid Mechanics": "Annu. Rev. Fluid Mech.",
  "Computer Physics Communications": "Comput. Phys. Commun.",
  "European Physical Letters": "EPL",
  "Fluid Dynamics Research": "Fluid Dyn. Res.",
  "Journal of Computational Physics": "J. Comput. Phys.",
  "Journal of Fluid Mechanics": "J. Fluid Mech.",
  "Journal of Statistical Physics": "J. Stat. Phys.",
  "Journal of the Atmospheric Sciences": "J. Atmos. Sci.",
  "Journal of Turbulence": "J. Turbul.",
  "Nature Communications": "Nat. Comm.",
  "New Journal of Physics": "New J. Phys.",
  "Physica D: Nonlinear Phenomena": "Physica D",
  "Physical Review E": "Phys. Rev. E",
  "Physical Review Fluids": "Phys. Rev. Fluids",
  "Physical Review Letters": "Phys. Rev. Lett.",
  "Physical Review Research": "Phys. Rev. Res.",
  "Physical Review X": "Phys. Rev. X",
  "Physics of Fluids": "Phys. Fluids",
  "Physics Reports": "Phys. Rep.",
  "Proceedings of the National Academy of Sciences": "Proc. Natl. Acad. Sci. USA",
  "Scientific Reports": "Sci. Rep.",
  "Theoretical and Applied Mechanics Letters": "Theor. App. Mech. Lett.",
)

#let abbreviate-journal(name) = journal-abbrev-map.at(name, default: name)
