#let journal-abbrev-map = (
  "Annual Review of Fluid Mechanics": "Annu. Rev. Fluid Mech.",
  "Computer Physics Communications": "Comput. Phys. Commun.",
  "Europhysics Letters": "EPL",
  "European Physical Letters": "EPL",
  "Experimental Fluids": "Exp. Fluids",
  "Fluid Dynamics Research": "Fluid Dyn. Res.",
  "Flow, Turbulence and Combustion": "Flow Turbul. Combust.",
  "International Journal of Heat and Fluid Flow": "Int. J. Heat Fluid Flow",
  "Journal of Computational Physics": "J. Comput. Phys.",
  "Journal of Fluid Mechanics": "J. Fluid Mech.",
  "Journal of Nonlinear Science": "J. Nonlinear Sci.",
  "Journal of Statistical Mechanics: Theory and Experiment": "J. Stat. Mech.",
  "Journal of Statistical Physics": "J. Stat. Phys.",
  "Journal of the Atmospheric Sciences": "J. Atmos. Sci.",
  "Journal of Turbulence": "J. Turbul.",
  "Nature Communications": "Nat. Commun.",
  "New Journal of Physics": "New J. Phys.",
  "Physica D: Nonlinear Phenomena": "Physica D",
  "Physical Review E": "Phys. Rev. E",
  "Physical Review Fluids": "Phys. Rev. Fluids",
  "Physical Review Letters": "Phys. Rev. Lett.",
  "Physical Review Research": "Phys. Rev. Res.",
  "Physical Review X": "Phys. Rev. X",
  "Physics of Fluids": "Phys. Fluids",
  "Physics Reports": "Phys. Rep.",
  "Physics Today": "Phys. Today",
  "Proceedings of the National Academy of Sciences": "Proc. Natl. Acad. Sci. USA",
  "Scientific Reports": "Sci. Rep.",
  "SIAM Journal on Applied Mathematics": "SIAM J. Appl. Math.",
  "Theoretical and Applied Mechanics Letters": "TAML",
)

#let abbreviate-journal(name) = journal-abbrev-map.at(name, default: name)
